<<<<<<< HEAD
# Provide gitlab ci configuration for upstream CI
# See https://github.com/QubesOS-contrib/qubes-skeleton/blob/master/.gitlab-ci.yml
include:
# Target 4.2 and newer only
=======
include:
- file: /r4.1/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.1/gitlab-dom0.yml
  project: QubesOS/qubes-continuous-integration
# It includes all the distributions
#- file: /r4.1/gitlab-vm.yml
#  project: QubesOS/qubes-continuous-integration
- file: /r4.1/gitlab-vm-fedora.yml
  project: QubesOS/qubes-continuous-integration
>>>>>>> 39d0c9d (Add .gitlab-ci and .qubesbuilder)
- file: /r4.2/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-host.yml
  project: QubesOS/qubes-continuous-integration
<<<<<<< HEAD
<<<<<<< HEAD
# It includes all the distributions
# - file: /r4.2/gitlab-vm.yml
  # project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-vm-fedora.yml
  project: QubesOS/qubes-continuous-integration
=======
- file: /r4.2/gitlab-vm.yml
=======
# It includes all the distributions
#- file: /r4.2/gitlab-vm.yml
#  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-vm-fedora.yml
>>>>>>> 11db931 (gitlab-ci: build only for Fedora)
  project: QubesOS/qubes-continuous-integration
>>>>>>> 39d0c9d (Add .gitlab-ci and .qubesbuilder)
