# Provide gitlab ci configuration for upstream CI
# See https://github.com/QubesOS-contrib/qubes-skeleton/blob/master/.gitlab-ci.yml
include:
# Target 4.2 and newer only
- file: /r4.2/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-host.yml
  project: QubesOS/qubes-continuous-integration
# It includes all the distributions
# - file: /r4.2/gitlab-vm.yml
  # project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-vm-fedora.yml
  project: QubesOS/qubes-continuous-integration