---
name: ci

on: [push, pull_request, merge_group]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:37
    steps:
      - run: dnf install -y git make rpmlint
      - name: Lint specfiles
        uses: actions/checkout@v4
        run: |
          rpmlint rpm_spec/*.spec
  build-rpm:
    runs-on: ubuntu-latest
    container:
      name: registry.gitlab.com/qubesos/docker-images/qubes-builder-debian:latest
    steps:
      - name: Clone qubes-builder
        uses: actions/checkout@v4
        with: https://github.com/QubesOS/qubes-builderv2
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Build RPM
        env: BRANCH_NAME: ${{ github.ref }}
        run: |
          make build-rpm BRANCH=${BRANCH_NAME}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: securedrop-workstation-keyring.rpm
          path: ../qubes-builderv2/artifacts/components/securedrop-workstation-keyring/*/host-fc37/build/rpm/securedrop-workstation-keyring-*.fc37.noarch.rpm
          persist-credentials: false
  # reprotest:
  #     runs-on: ubuntu-latest
  #     container:
  #       image: registry.fedoraproject.org/fedora:37
  #     steps:
  #       - run: dnf install -y git make reprotest
  #       - name: Download rpm
  #         uses: actions/download@v4
  #         with:
  #           name: securedrop-workstation-keyring.rpm
  #           persist-credentials: false
  #       - name: Test reproducibility
  #         run: |
  #           sudo reprotest securedrop-workstation-keyring.rpm
  #           'make build-rpm' --variations '+all,+kernel,-time,-fileordering,-domain_host'"