---
name: ci

on: [push, pull_request, merge_group]

jobs:
  lint-and-build:
    uses: freedomofpress/securedrop-workstation-keyring/.github/workflows/lint-and-build.yml@main
    with:
      target-branch: ${{ github.head_ref || github.ref_name }}
