---
name: ci

on: [push, pull_request, merge_group]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: quay.io/fedora/fedora:37
    steps:
      - run: dnf install -y git make rpmlint
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: |
          git config --global --add safe.directory '*'
          rpmlint rpm_spec/*.spec
  check-signing-key:
    runs-on: ubuntu-latest
    container: debian:trixie
    steps:
      - name: Bootstrap Debian system package dependencies
        run: |
          apt-get update && apt-get install --yes --no-install-recommends sudo git git-lfs \
          ca-certificates python3-dev sq
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Check key expiry and metadata
        run: |
          python3 ./scripts/check-signing-key-expiry.py
  build-rpm:
    strategy:
      matrix:
        qubes_release: ["4.2", "4.3"]
    runs-on: ubuntu-latest
    needs: [ "lint" ]
    # merge queue branch name confuses the builder
    if: |
      !startsWith( github.ref, 'refs/heads/gh-readonly-queue/' )
    env:
      CI_SKIP_PREREQS: 1
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: QubesOS/qubes-builderv2
          path: qubes-builderv2
      - name: Fetch latest qubes-builder tag
        run: |
          cd ${{ github.workspace }}/qubes-builderv2/
          git fetch --depth=1 origin "refs/tags/*:refs/tags/*"
      - uses: actions/checkout@v4
        with:
          path: securedrop-workstation-keyring
      # See Makefile and CI_SKIP_PREREQS flag.
      # GHA image has docker preinstalled
      - name: Install Qubes-builderv2 dependencies
        run: |
          grep -v "^docker\.io$" ${{ github.workspace }}/qubes-builderv2/dependencies-debian.txt | xargs sudo apt install -y -
      - name: Build container image
        run: |
          cd ${{ github.workspace }}/qubes-builderv2
          ./tools/generate-container-image.sh docker
      - name: Edit apparmor profile for unix-chkpwd
        run: |
          sudo sed -i 's/capability audit_write,$/&\n  # fix: read shadow permissions (linux-pam#686)\n  capability dac_read_search,/' /etc/apparmor.d/unix-chkpwd
          sudo apparmor_parser -r /etc/apparmor.d/unix-chkpwd
      - name: Build rpm (Qubes ${{ matrix.qubes_release }})
        run: |
          sudo apt install -y python3-pathspec
          cd ${{ github.workspace }}/securedrop-workstation-keyring
          make build-rpm BUILD_CONTAINER=docker BRANCH=${{ env.BRANCH_NAME }} QUBES_RELEASE=${{ matrix.qubes_release }}
      - name: Test Correct repo version
        run: |
          sudo apt install -y rpm2cpio
          cd ${{ github.workspace }}/securedrop-workstation-keyring/build/
          expected_dom0_fedora=${{ fromJson('{"4.2": "fc37", "4.3": "fc41"}')[matrix.qubes_version] }}
          rpm2cpio *.rpm | grep --text "baseurl=.*$expected_dom0_fedora"
      - name: Upload RPM
        uses: actions/upload-artifact@v4
        id: rpm-upload-step
        with:
          name: rpm-${{ env.BRANCH_NAME }}-${{ matrix.qubes_release }}
          path: ${{ github.workspace }}/securedrop-workstation-keyring/build/*.rpm
          retention-days: 5
          if-no-files-found: error
