---
name: ci

on: [push, pull_request, merge_group]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:37
    steps:
      - run: dnf install -y git make
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install dependencies
        run: |
          make test-deps
      - name: Run linters
        run: |
          git config --global --add safe.directory '*'
          make lint
  build-rpm:
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:37
    steps:
      - run: dnf install -y git make
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install dependencies
        run: |
          make test-deps
      - name: Build RPM
        run: |
          git config --global --add safe.directory '*'
          make prepare
          make build-rpm
      - name: Check reproducibility
        run: |
          make test-deps
          make reprotest
